### PR TITLE
Set autocomplete properties for password fields

### LINKED ISSUE #74: Avoid browsers prompting for storing new password
Admin reset user's password.

Browser proposes to store new password.

 Maybe use text input type text instead of input type password  and obfuscate by using JS.

### PR DESCRIPTION
**Pull request by coudot**
Should close #74

### CODE REVIEW

**Comment by coudot** [comment]
@cmaudoux could you test this change?

**Comment by cmaudoux** [comment]
Browser still prompts for storing password...

**Comment by coudot** [comment]
Browsers are indeed not respecting the standard...

We can give a try to https://stackoverflow.com/questions/59991469/chrome-firefox-autocomplete-new-password-not-working

**Comment by coudot** [comment]
Hello @cmaudoux 

here is a code to test the workaround: https://github.com/ltb-project/service-desk/pull/83/commits/c5b3bee521a47a04062bbf56efdc6ab792f5991e

**Comment by coudot** [comment]
Added this trick as an official option.

From my point of view it is ready to merge.

**Pull request merged**
