### PR TITLE
Update general-parameters.rst

### PR DESCRIPTION
**Pull request by cmaudoux**
Fix multi tenancy Nginx conf. snippet

### CODE REVIEW

**Comment by cmaudoux** [comment]
Let you check if Apache2 conf. snippet is correct

**Comment by cmaudoux** [comment]
Does not work anymore...

**Comment by coudot** [comment]
What is the issue?

**Comment by cmaudoux** [comment]
My bad. The issue exists.

**Comment by cmaudoux** [comment]
My conf :
$header_name_extra_config = "SSP-Extra-Config";

    # pass PHP scripts to FastCGI server
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_param HTTP_SSP_EXTRA_CONFIG domain1;
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
    }

It works with this conf.

**Pull request merged**
